src/Entity/DemandeConge.php
<?php

namespace App\Entity;

use App\Repository\DemandeCongeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DemandeCongeRepository::class)
 */
class DemandeConge
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $MotifConge;

    /**
     * @return mixed
     */
    public function getMotifConge()
    {
        return $this->MotifConge;
    }

    /**
     * @param mixed $MotifConge
     */
    public function setMotifConge($MotifConge): void
    {
        $this->MotifConge = $MotifConge;
    }



    /**
     * @return mixed
     */
    public function getDateDepart()
    {
        return $this->DateDepart;
    }

    /**
     * @param mixed $DateDepart
     */
    public function setDateDepart($DateDepart): void
    {
        $this->DateDepart = $DateDepart;
    }
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateDepart;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateRetour;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateDemande;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Etat;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="Demandes")
     */
    private $user;





    public function __construct()
    {


        $this->setDateDemande(new \DateTime());

    }

//    /**
//     * @ORM\ManyToOne(targetEntity=Employees::class, inversedBy="demandeConges")
//     */
//    private $employee;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getDateRetour()
    {
        return $this->DateRetour;
    }

    /**
     * @param mixed $DateRetour
     */
    public function setDateRetour($DateRetour): void
    {
        $this->DateRetour = $DateRetour;
    }





    public function getDateDemande(): ?\DateTimeInterface
    {
        return $this->DateDemande;
    }

    public function setDateDemande(?\DateTimeInterface $DateDemande): self
    {
        $this->DateDemande = $DateDemande;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(?string $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

//    public function getEmployee(): ?Employees
//    {
//        return $this->employee;
//    }
//
//    public function setEmployee(?Employees $employee): self
//    {
//        $this->employee = $employee;
//
//        return $this;
//    }

public function getUser(): ?User
{
    return $this->user;
}

public function setUser(?User $user): self
{
    $this->user = $user;

    return $this;
}




}

src/Entity/Projets.php
<?php

namespace App\Entity;

use App\Repository\ProjetsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjetsRepository::class)
 */
class Projets
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Projet;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Statut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Departement;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateFin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProjet(): ?string
    {
        return $this->Projet;
    }

    public function setProjet(?string $Projet): self
    {
        $this->Projet = $Projet;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(?string $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->Departement;
    }

    public function setDepartement(string $Departement): self
    {
        $this->Departement = $Departement;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @method string getUserIdentifier()
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")

 */
class User  implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json", length=255, nullable=true)
     */
    private $roles;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */





    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $grade;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $departement;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Salaire;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $cin;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_embauche;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
//entity
    private $role;

    /**
     * @ORM\OneToMany(targetEntity=DemandeConge::class, mappedBy="user")
     */
    private $Demandes;

    public function __construct()
    {
        $this->Demandes = new ArrayCollection();
    }






    public function setRole($role){
        $this->roles = $role;
        return $this;
    }

    public function getRole(){
        return $this->roles;
    }
    public function getRoles(): ?array
    {
        return $this->roles;
    }

    public function setRoles(?string $roles): self
    {
        $this->roles = $roles;
        return $this;

    }


    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getSalt()
    {
         return ' ' ;
    }

    public function eraseCredentials()
    {
        return ' ' ;
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function __call($name, $arguments)
    {
        return $this ;
    }

    public function getGrade(): ?string
    {
        return $this->grade;
    }

    public function setGrade(?string $grade): self
    {
        $this->grade = $grade;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(?string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSalaire(): ?int
    {
        return $this->Salaire;
    }

    public function setSalaire(?int $Salaire): self
    {
        $this->Salaire = $Salaire;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(?string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->date_embauche;
    }

    public function setDateEmbauche(?\DateTimeInterface $date_embauche): self
    {
        $this->date_embauche = $date_embauche;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    /**
     * @return Collection|DemandeConge[]
     */
    public function getDemandes(): Collection
    {
        return $this->Demandes;
    }

    public function addDemande(DemandeConge $demande): self
    {
        if (!$this->Demandes->contains($demande)) {
            $this->Demandes[] = $demande;
            $demande->setUser($this);
        }

        return $this;
    }

    public function addRole(String $role): self
    {
        $this->roles[] = $role;


        return $this;
    }

    public function removeDemande(DemandeConge $demande): self
    {
        if ($this->Demandes->removeElement($demande)) {
            // set the owning side to null (unless already changed)
            if ($demande->getUser() === $this) {
                $demande->setUser(null);
            }
        }

        return $this;
    }






    
}

templates/home/Conges.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#exampleModal">
        Demander un Congé
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Demander un Congé</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="Conges" method="post">


    {#                        <div class="form-row">#}
    {#                            <div class="form-group col-md-6">#}

    {#                                <input type="text" class="form-control" value="{{ app.user.id }}" name="Employee" id="Employee" >#}
    {#                            </div>#}
    {#                        </div>#}

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="MotifConge">Motif de Congé</label>
                                <input type="text" class="form-control" name="MotifConge" id="MotifConge">
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="DateDepartConge">Date de Depart de Congé</label>
                                <input type="date" class="form-control" name="DateDepartConge" id="DateDepartConge">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="DateFinConge">Date de Fin de Congé</label>
                                <input type="date" class="form-control" name="DateFinConge" id="DateFinConge">
                            </div>
                        </div>








                        <button type="submit" class="btn btn-primary ">Demander</button>
                        <button type="button" class="btn btn-secondary " data-dismiss="modal">Fermer</button>
                    </form>


                </div>
                <div class="modal-footer">


                </div>
            </div>
        </div>



    </div>

{#   <pre> {{ dump(app.user) }}</pre>#}
    <div class="container-fluid">
        <br>
        <h3 class="text-dark mb-4"></h3>
        <div class="card shadow">
            <div class="card-header py-3">
                <p class="text-primary m-0 font-weight-bold">Demandes de Congés</p>
            </div>
            <div class="card-body">

<div class="table-responsive" style="overflow: hidden">

    <table id="example" class="datatable table table-striped table-bordered"  >
        <thead>
        <tr>
            <th>Name</th>
            <th>Date de Demande</th>
            <th>Date de Depart</th>
            <th>Date de Retour</th>
            <th>Motif</th>
            <th>Etat</th>

        </tr>
        </thead>
        <tbody>

        {% if is_granted("ROLE_ADMIN") %}

{#                <tr>#}
{#                    <td>{{ app.user.email }}</td>#}

{#                </tr>#}

            {% for data in conges %}
                <tr>

                    <td>{{ data.user.name }}   </td>
                    <td> {{ data.dateDemande|date('Y-m-d') }}</td>
                    <td> {{ data.dateDepart|date('Y-m-d') }}</td>
                    <td> {{ data.dateRetour|date('Y-m-d') }}</td>
                    <td> {{ data.motifConge }}</td>
                    <td> {{ data.etat }}</td>
                    {% if data.etat!='Approuvé' and data.etat!='Refusé'  %}
                        <td>
                            <form action="{{ path('etatApprouver', {'id': data.id}) }}" method="post">
                                <input type="submit" value="✔" name="approuver" class="btn btn-success btn-sm btn-block">
                            </form>

                        </td>
                        <td>
                            <form action="{{ path('etatRefuser', {'id': data.id}) }}" method="post">
                                <input type="submit" value="❌" name="Refuser" class="btn btn-danger btn-sm btn-block">
                            </form>
                        </td>
                    {% endif %}



                </tr>
            {% endfor %}
        {% else %}
       {% for data in conges%}       {#     |filter(e => e.employee == app.user)#}
                {#            {% for data in conges %}#}
                <tr>

                    <td>{{ data.user.name  }}</td>
                    <td> {{ data.dateDemande|date('d-m-Y') }}</td>
                    <td> {{ data.dateDepart|date('d-m-Y')  }}</td>
                    <td> {{ data.dateRetour|date('d-m-Y')  }}</td>
                    <td> {{ data.motifConge }}</td>
                    <td> {{ data.etat }}</td>


                </tr>
            {% endfor %}


        {% endif %}


        </tbody>

    </table>
</div>




            </div>
        </div>
    </div>



{% endblock %}

templates/home/Profile.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div id="wrapper">

        <div class="container-fluid  ">
            <h3 class="text-dark mb-4 d-flex justify-content-center ">Profile</h3>
            <div class=" d-flex justify-content-center  row mb-3">

                <div class=" col-lg-8">
                    <div class="card  mb-3">

                        <div class="card-body text-center shadow "><img class="rounded-circle mb-3 mt-4" src="assets/img/dogs/image2.jpeg" width="160" height="160">
                            <div class="mb-3"><i>{{ app.user.name }}</i></div>
                        </div>
                    </div>

                </div>
                <div class="col-lg-8">

                    <div class="row">
                        <div class=" col">
                            <div class="card  shadow mb-3">
                                <div class="card-header py-3">
                                    <p class="text-primary m-0 font-weight-bold">User Settings</p>
                                </div>
                                <div class="  card-body">

                                        <div class="form-row">
                                            <div class="col">
                                                <div class="form-group"><label for="email"><strong>Adresse&nbsp;Email</strong></label><input class="form-control" type="email" placeholder="{{app.user.email}}" name="email" disabled></div>
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="col-md-4">
                                                <div class="form-group"><label for="name"><strong>Nom et Prenom</strong><br></label><input class="form-control" type="text" placeholder="{{ app.user.name }}" name="name" disabled></div>
                                            </div>

                                        </div>
                                    <div class="form-row">
                                        <div class="col-md-4">
                                            <div class="form-group"><label for="tel"><strong>Tel</strong><br></label><input class="form-control" type="text" placeholder="{{ app.user.tel }}" name="tel" disabled></div>
                                        </div>

                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-4">
                                            <div class="form-group"><label for="Salaire"><strong>Salaire</strong><br></label><input class="form-control" type="text" placeholder="{{ app.user.salaire }} DH" name="Salaire" disabled></div>
                                        </div>

                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-4">
                                            <div class="form-group"><label for="datenaissance"><strong>Date de Naissance</strong><br></label><input class="form-control" type="text" placeholder="{{ app.user.dateNaissance|date('d-m-Y') }}" name="datenaissance" disabled></div>
                                        </div>

                                    </div>


                                </div>
                            </div>
                            <div class="card shadow">
                                <div class="card-header py-3">
                                    <p class="text-primary m-0 font-weight-bold">Contact</p>
                                </div>
                                <div class="card-body">

                                        <div class="form-group"><label for="address"><strong>Addresse</strong></label><input class="form-control" type="text" placeholder="{{ app.user.adresse }}" name="address" disabled></div>
                                        <div class="form-row">
                                            <div class="col">
                                                <div class="form-group"><label for="city"><strong>Ville</strong></label><input class="form-control" type="text" placeholder="Oujda" name="city" disabled></div>
                                            </div>
                                            <div class="col">
                                                <div class="form-group"><label for="country"><strong>Pays</strong></label><input class="form-control" type="text" placeholder="Maroc" name="country" disabled></div>
                                            </div>
                                        </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


{% endblock %}

templates/home/Projets.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#exampleModal">
        Ajouter un Projet
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Projets</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ path('Projets') }}" method="POST">


                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="Projet">Projet</label>
                                <input type="text" class="form-control" name="Projet" id="Projet">
                            </div>
                        </div>



                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="Departement">Departement</label>
                                <select id="Departement"  name="Departement" class="form-control">
                                    <option selected>Division a</option>
                                    <option selected>Division b</option>
                                </select>
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="DateDebut">Date de Debut</label>
                                <input type="date" class="form-control" name="DateDebut" id="DateDebut">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="DateFin">Date de Fin</label>
                                <input type="date" class="form-control" name="DateFin" id="DateFin">
                            </div>
                        </div>




                        <button type="submit" class="btn btn-primary">Ajouter</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    </form>
                </div>
                <div class="modal-footer">


                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
<br>
        <h3 class="text-dark mb-4"></h3>
        <div class="card shadow">
            <div class="card-header py-3">
                <p class="text-primary m-0 font-weight-bold">Projets</p>
            </div>
            <div class="card-body">
                <table id="example" class="table table-striped table-bordered" style="overflow:hidden;width:100%">
                    <thead>
                    <tr>
                        <th>Projet</th>


                        <th>DateDebut</th>
                        <th>DateFin</th>
                        <th>Statut</th>
                        <th>Departement</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>

                    {% for data in Projets %}
                        <tr>

                            <td>{{ data.Projet }} </td>
                            <td> {{ data.dateDebut|date('d-m-Y')  }}</td>
                            <td> {{ data.dateFin|date('d-m-Y')  }}</td>
                            <td> {{ data.statut }}</td>
                            <td> {{ data.Departement }}</td>
                            <td>

                                {% if data.statut=='Fini' %}


                                            <form action="{{ path('Action', {'id': data.id,'Action': 'En cours'}) }}" method="POST">
                                                <input type="submit" value="Marquer comme non fini" name="Terminer" class="btn btn-success btn-sm btn-block">
                                            </form>
                                            <form action="{{ path('SupprimerProjet', {'id': data.id}) }}" method="POST">
                                                <input type="submit" value="Supprimer" name="Supprimer" class="btn btn-danger btn-sm btn-block">
                                            </form>



                                {% endif %}
                                {% if data.statut=='En cours' %}
                                    <form action="{{ path('Action', {'id': data.id,'Action': 'Fini'}) }}" method="POST">
                                        <input type="submit" value="Terminer" name="Terminer" class="btn btn-danger btn-sm btn-block">
                                    </form>
                                {% endif %}



                            </td>
                        </tr>
                    {% endfor %}


                    </tbody>
                    <tfoot>

                    </tfoot>
                </table>


            </div>
        </div>
    </div>
{% endblock %}